install:
    - wget https://luarocks.org/releases/luarocks-3.3.0.tar.gz
    - tar zxpf luarocks-3.3.0.tar.gz
    - cd luarocks-3.3.0
    - ./configure && make && sudo make install
    - luarocks install luacheck
script:
    - luarocks *.lua
