install:
    - apt update
    - apt install lua5.3
    - wget https://luarocks.org/releases/luarocks-3.3.0.tar.gz
    - tar zxpf luarocks-3.3.0.tar.gz
    - cd luarocks-3.3.0
    - ./configure && make && sudo make install
    - luarocks install luacheck
script:
    - luarocks *.lua
    - zip -9 -r bornholm.love .

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "bornholm*.love"
    skip_cleanup: true
    on:
        tags: true
